// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhadotwrcwfpteopnmmx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoYWRvdHdyY3dmcHRlb3BubW14Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjYyNDIsImV4cCI6MjA2NDM0MjI0Mn0.m83aT2tM2kSa-8MINmM1g18RKvqNkBMAQq6TndSsisA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);